application: talk-org
version: 1
runtime: python
api_version: 1

handlers:

# If we match a version string, map to a static file
# and also send a far-future expires header for caching that version.
# i.e /js/talk.1.24.js will send down the contents of /static/js/talk.js
# but with an Expires header of +10 years from today.
- url: /(javascripts|stylesheets|images)/(.+)\.\d+\.\d+\.(js|css|png|gif|jpg)
  static_files: static/\1/\2.\3
  upload: static/(javascripts|stylesheets|images)/(.+)\.\d+\.\d+\.(js|css|png|gif|jpg)
  expiration: '3650d'
                        
# Default static content url catches those w/o versions in their names.
- url: /(javascripts|stylesheets|images)/(.*\.(js|css|png|gif|jpg))
  static_files: static/\1/\2
  upload: static/(javascripts|stylesheets|images)/(.*\.(js|css|png|gif|jpg))

# Default static content url catches those w/o versions in their names.
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

# Pass everything else to the django bootstrapper.
- url: /.*
  script: django_bootstrap.py
